name: cords2022
channels:
- fastai
- conda-forge
- gurobi
- defaults
dependencies:
- python=3.9
- pip
- ipykernel
- numpy
- matplotlib
- pandas
- scipy
- scikit-learn
- numba
- ngboost
- statsmodels
- scikit-optimize
- pip:
  - mip
